# Generated by Django 3.0.2 on 2020-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filetype', models.PositiveIntegerField(choices=[(1, 'PDF'), (2, 'DOC')], default=1)),
            ],
        ),
    ]
